package odooclient

import (
	"context"
	"errors"
	"os"
	"testing"
	"time"

	"trigger/apps/web/common/sales"
)

func TestMain(m *testing.M) {
	loadEnv()
	os.Exit(m.Run())
}

// newTestClient skips the test when no API key is available (e.g. CI), so the
// suite degrades gracefully outside a developer machine with Odoo running. It
// reads the same CRM_* keys the app itself uses (from config/dev.env).
func newTestClient(t *testing.T) sales.CRM {
	t.Helper()
	key := os.Getenv("CRM_API_KEY")
	if key == "" {
		t.Skip("CRM_API_KEY not set; skipping Odoo integration test")
	}
	base := os.Getenv("CRM_BASE_URL")
	if base == "" {
		base = "http://localhost:8069"
	}
	c, err := NewClient(sales.CRMConfig{Provider: "odoo", BaseURL: base, APIKey: key})
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}
	return c
}

func TestLeadList(t *testing.T) {
	c := newTestClient(t)
	ctx := context.Background()

	page, err := c.LeadList(ctx, sales.LeadFilter{Limit: 5})
	if err != nil {
		t.Fatalf("LeadList: %v", err)
	}
	if page.Count == nil || *page.Count == 0 {
		t.Fatal("expected leads in demo data, got count=0")
	}
	if len(page.Results) == 0 {
		t.Fatal("expected results, got none")
	}

	l := page.Results[0]
	if l.ID == "" || l.Name == "" {
		t.Fatalf("lead not adapted: %+v", l)
	}
	if l.Budget.Currency == "" {
		t.Errorf("budget currency not mapped: %+v", l.Budget)
	}
	if l.Tags == nil {
		t.Error("Tags should be a non-nil slice even when empty")
	}
	t.Logf("first lead: id=%s name=%q stage=%q budget=%v tags=%v", l.ID, l.Name, l.Stage, l.Budget, l.Tags)
}

func TestLeadFind(t *testing.T) {
	c := newTestClient(t)
	ctx := context.Background()

	page, err := c.LeadList(ctx, sales.LeadFilter{Limit: 1})
	if err != nil || len(page.Results) == 0 {
		t.Fatalf("need a lead to fetch: %v", err)
	}
	id := page.Results[0].ID

	detail, err := c.LeadFind(ctx, id)
	if err != nil {
		t.Fatalf("LeadFind(%s): %v", id, err)
	}
	if detail.ID != id {
		t.Errorf("detail id = %s, want %s", detail.ID, id)
	}
	if detail.OpenActivities == nil {
		t.Error("OpenActivities should be a non-nil slice")
	}
	t.Logf("lead %s: partner=%q team=%q deadline=%s open_activities=%d",
		detail.ID, detail.Partner, detail.SalesTeam, detail.Deadline, len(detail.OpenActivities))
}

func TestProjectListAndFind(t *testing.T) {
	c := newTestClient(t)
	ctx := context.Background()

	page, err := c.ProjectList(ctx, sales.ProjectFilter{Limit: 1})
	if err != nil {
		t.Fatalf("ProjectList: %v", err)
	}
	if len(page.Results) == 0 {
		t.Fatal("expected projects in demo data")
	}
	p := page.Results[0]
	if p.ID == "" || p.Name == "" {
		t.Fatalf("project not adapted: %+v", p)
	}

	detail, err := c.ProjectFind(ctx, p.ID)
	if err != nil {
		t.Fatalf("ProjectFind(%s): %v", p.ID, err)
	}
	if detail.ID != p.ID {
		t.Errorf("detail id = %s, want %s", detail.ID, p.ID)
	}
	t.Logf("project %s (%s): units=%d delivery=%s price_from=%v",
		detail.ID, detail.Name, len(detail.Units), detail.DeliveryDate, detail.PriceFrom)
}

func TestUnitList(t *testing.T) {
	c := newTestClient(t)
	ctx := context.Background()

	page, err := c.UnitList(ctx, sales.UnitFilter{State: "available", Limit: 3})
	if err != nil {
		t.Fatalf("UnitList: %v", err)
	}
	if len(page.Results) == 0 {
		t.Fatal("expected available units in demo data")
	}
	u := page.Results[0]
	if u.State != "available" {
		t.Errorf("state filter leaked: got %q", u.State)
	}
	if u.Price.Currency == "" {
		t.Errorf("price currency not mapped: %+v", u.Price)
	}
	t.Logf("unit %s: code=%q type=%q beds=%d price=%v", u.ID, u.Code, u.Type, u.Bedrooms, u.Price)
}

func TestActivityList(t *testing.T) {
	c := newTestClient(t)
	ctx := context.Background()

	page, err := c.ActivityList(ctx, sales.ActivityFilter{PageSize: 3})
	if err != nil {
		t.Fatalf("ActivityList: %v", err)
	}
	if page.Count == nil || *page.Count == 0 {
		t.Fatal("expected activities in demo data, got count=0")
	}
	a := page.Results[0]
	if a.ID == "" {
		t.Fatalf("activity not adapted: %+v", a)
	}
	t.Logf("activity %s: summary=%q state=%q deadline=%s lead=%q",
		a.ID, a.Summary, a.State, a.Deadline, a.Lead)
}

// TestActivityScheduleAndComplete exercises the full write path. Completing
// deletes the activity in Odoo and writes a chatter message, so the net effect
// on the demo DB is one new chatter line - acceptable for a local test Odoo.
func TestActivityScheduleAndComplete(t *testing.T) {
	c := newTestClient(t)
	ctx := context.Background()

	leads, err := c.LeadList(ctx, sales.LeadFilter{Limit: 1})
	if err != nil || len(leads.Results) == 0 {
		t.Fatalf("need a lead to attach an activity: %v", err)
	}
	leadID := leads.Results[0].ID

	created, err := c.ActivitySchedule(ctx, sales.ActivityDraft{
		LeadID:       leadID,
		Summary:      "Trigger integration test follow-up",
		Note:         "auto-generated by odooclient integration test",
		Deadline:     time.Now().AddDate(0, 0, 2),
		ActivityType: "mail.mail_activity_data_todo",
	})
	if err != nil {
		t.Fatalf("ActivitySchedule: %v", err)
	}
	if created.ID == "" {
		t.Fatalf("created activity has no id: %+v", created)
	}
	t.Logf("scheduled activity %s on lead %s", created.ID, leadID)

	result, err := c.ActivityComplete(ctx, created.ID, "done from integration test")
	if err != nil {
		t.Fatalf("ActivityComplete(%s): %v", created.ID, err)
	}
	if result.Completed.ID != created.ID {
		t.Errorf("completed id = %s, want %s", result.Completed.ID, created.ID)
	}
	if result.AuditRef == "" {
		t.Error("expected AuditRef (Odoo message_id) on completion")
	}
	t.Logf("completed activity %s; audit_ref=%s", result.Completed.ID, result.AuditRef)
}

// --- Error mapping ---------------------------------------------------------

func TestErrorAuth_badKey(t *testing.T) {
	base := os.Getenv("CRM_BASE_URL")
	if base == "" {
		base = "http://localhost:8069"
	}
	c, err := NewClient(sales.CRMConfig{Provider: "odoo", BaseURL: base, APIKey: "definitely-not-a-real-key"})
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}

	_, err = c.LeadList(context.Background(), sales.LeadFilter{Limit: 1})
	if !errors.Is(err, sales.ErrAuth) {
		t.Fatalf("expected ErrAuth, got %v", err)
	}
}

func TestErrorNotFound_badLeadID(t *testing.T) {
	c := newTestClient(t)
	_, err := c.LeadFind(context.Background(), "999999999")
	if !errors.Is(err, sales.ErrNotFound) {
		t.Fatalf("expected ErrNotFound, got %v", err)
	}
}
